deathban-time:
  days: 0
  hours: 24
  minutes: 0
drop-enderchest-on-death: true

# Hardcore24 requires some further configuration to work, which *can* be done using the json files, but I very, very, very strongly recommend using the commands below to do this instead...
###                            EXAMPLE SETUP:                                 ###
#        /group CREATE_GROUP demo_group                                         #
#        Here we create a group called demo_group                               #
#                                                                               #
#        /group SET_RESPAWN                                                     #
#        Next we run this command, while at the respawn location we want        #
#                                                                               #
#        /group SET_WORLD world demo_group                                      #
#        Here we add the world "world" to our group                             #
#                                                                               #
#        /group SET_WORLD lobby demo_group                                      #
#        Here we also add the world "lobby" to our group                        #
#                                                                               #
###                                                                           ###