respawn-location:
  x: 0.0
  y: 0.0
  z: 0.0
  world: world
# The world they get sent to after respawning
#
hardcore-world:
  hardcore-normal: hardcore
  hardcore-nether: hardcore_nether
  hardcore-end: hardcore_end
# Configure the hardcore worlds
# Note: If you don't have a nether and end world then rename them to a world that doesn't exist
hardcore-config:
  harder-mobs: false
  do-blood-moon: false
  blood-moon-duration: 2.0
  # in hrs (above)
  death-ban-time: 24.0
  leader-board: false
  death-ban-exclude-ops: true
  # ^ above is the time you want to ban the player for in hours ^
