name: Hardcore24
version: '2.44'
main: uk.co.shadowtrilogy.hardcore24.Hardcore24
api-version: '1.20'
load: STARTUP
authors: [BlueNightFury46]
description: a 24 hour (default) hardcore death timeout plugin
website: shadowtrilogy.co.uk
commands:
  hardcore:
    description: The hardcore24 general purpose command
    usage: /<command> <action> <player-name>
  hardcore24-version:
    description: Displays the current hardcore24 version
    usage: /<hardcore24-version>
    aliases:
      - version
      - hardcore-version
permissions:
  hardcore.commands:
   description: Allows players to use the /Hardcore command

