name: Hardcore24
version: '1.0'
main: uk.co.shadowtrilogy.hardcore24.Hardcore24
api-version: '1.20'
load: STARTUP
authors: [BlueNightFury46]
description: a 24 hour (default) hardcore death timeout plugin
website: shadowtrilogy.co.uk
commands:
  hardcore:
    description: Your description
    usage: /<command> [add|remove|permissions-add/remove] <player-name>
