respawn-location:
  x: 0.0
  y: 0.0
  z: 0.0
  world: world
# The world they get sent to after respawning
#
hardcore-world:
  hardcore-normal: hardcore
  hardcore-nether: hardcore_nether
  hardcore-end: hardcore_end
# Configure the hardcore worlds
#
